def test():
    raise Exception('on purpose')
